export default {
    'booking-form-editor-form-component-template-divider': require('@/components/BookingFormEditor/FormComponentTemplates/divider/component.vue').default,
    'booking-form-editor-form-component-template-spacer': require('@/components/BookingFormEditor/FormComponentTemplates/spacer/component.vue').default,
    'booking-form-editor-form-component-template-text': require('@/components/BookingFormEditor/FormComponentTemplates/text/component.vue').default,
    'booking-form-editor-form-component-template-label': require('@/components/BookingFormEditor/FormComponentTemplates/label/component.vue').default,
    'booking-form-editor-form-component-template-textfield': require('@/components/BookingFormEditor/FormComponentTemplates/textfield/component.vue').default,
    'booking-form-editor-form-component-template-textarea': require('@/components/BookingFormEditor/FormComponentTemplates/textarea/component.vue').default,
    'booking-form-editor-form-component-template-select': require('@/components/BookingFormEditor/FormComponentTemplates/select/component.vue').default,
    'booking-form-editor-form-component-template-image': require('@/components/BookingFormEditor/FormComponentTemplates/image/component.vue').default,
    'booking-form-editor-form-component-template-services': require('@/components/BookingFormEditor/FormComponentTemplates/services/component.vue').default,
    'booking-form-editor-form-component-template-bookingspotdate': require('@/components/BookingFormEditor/FormComponentTemplates/bookingSpotDate/component.vue').default,
    'booking-form-editor-form-component-template-bookingspottime': require('@/components/BookingFormEditor/FormComponentTemplates/bookingSpotTime/component.vue').default,
    'booking-form-editor-form-component-template-frequencies': require('@/components/BookingFormEditor/FormComponentTemplates/frequencies/component.vue').default,
    'booking-form-editor-form-component-template-extras': require('@/components/BookingFormEditor/FormComponentTemplates/extras/component.vue').default,
    'booking-form-editor-form-component-template-serviceoptions': require('@/components/BookingFormEditor/FormComponentTemplates/serviceOptions/component.vue').default,
    'booking-form-editor-form-component-template-paymentmethods': require('@/components/BookingFormEditor/FormComponentTemplates/paymentMethods/component.vue').default,
    'booking-form-editor-form-component-template-bookingsummary': require('@/components/BookingFormEditor/FormComponentTemplates/bookingSummary/component.vue').default,
    'booking-form-editor-form-component-template-button': require('@/components/BookingFormEditor/FormComponentTemplates/button/component.vue').default,
    'booking-form-editor-form-component-template-checkbox': require('@/components/BookingFormEditor/FormComponentTemplates/checkbox/component.vue').default,
    'booking-form-editor-form-component-template-radio': require('@/components/BookingFormEditor/FormComponentTemplates/radio/component.vue').default,
    'booking-form-editor-form-component-template-termofservice': require('@/components/BookingFormEditor/FormComponentTemplates/termOfService/component.vue').default,
}